### ISSUE TITLE
Injecting a SerializerInterface

### ISSUE THREAD

**Issue by qpautrat** [woohoolabs/yin#19]
Hello Woohoolabs !
How are you ?

How do you think about instead hard coded [`json_encode()`](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Document/AbstractSuccessfulDocument.php#L148) using a `SerializerInterface` which could be injected in `Document` ?

Through this we could be able to inject any Serializer (i'm thinking about JMSSerializer right now) and use it.

Thoughts ?

**Comment by qpautrat** [comment]
Nevermind. I think i have misunderstood something here.
In fact we have a multi-versioning issue. 
But as our resource which will be serialized is dynamically built, it is impossible to use JMS Serializer like the way it is.
So my proposal is shit actually.
Have you already thought about it ? Instead of buid our resource with `getAttributes()` for example we can just serialize whole object and then rely on a more powerful serializer to get attributes we want.

**Comment by kocsismate** [comment]
Sorry for the delayed answer, but welcome back :) 

In another project of mine, I also tried to use JMSSerializer, but I also had to take it down because of some issues.

I have been trying to imagine how your second proposal could work, but I couldn't find it out yet. :S Could you please elaborate your idea? The problem I see now is that serialization is completely based on the `ResourceTransformerInterface`, so even relationships need it. I don't think it can be avoided.

I am looking forward to hearing about your feedback!

**Comment by qpautrat** [comment]
Hi !
I tried it too and like you i didn't find a proper way to do it.

**Comment by kocsismate** [comment]
I am closing this issue for now, but if you have any other idea, feel free to create a new ticket or reopen this one :)

**Comment by kocsismate** [comment]
Hey @qpautrat ,

Look at my commit https://github.com/woohoolabs/yin/commit/d3ab178dccf8d8ed6442d14fd5c48065a79c9821! I've just implemented what you asked for (or maybe something close to it), because I want to do something in my side-project which needs the ability to serializate messages in a custom way.

I hope that you'll like this feature :)

**Comment by qpautrat** [comment]
Hey !

Ok, I think you forgot something here.
You should pass your `serializer` attribute [here](https://github.com/woohoolabs/yin/blob/d3ab178dccf8d8ed6442d14fd5c48065a79c9821/src/JsonApi/JsonApi.php#L109) i assumed, no ?
Your tests should not passed there.
But except this point, IMO this PR should do the stuff.  Nice job !

**Comment by kocsismate** [comment]
Very nice catch :P But Scrutinizer also warned me, so I fixed this immediately in another commit https://github.com/woohoolabs/yin/commit/8a6ac1719342b8ef76e47b1d0ed029ef46d9fcb7

Anyway, you are right, a good test suite should have caught this issue! I plan to improve the coverage until releasing Yin 1.0.

Thank you for the feedback!
